spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/rental_manager
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  redis:
    host: rental-redis
    port: 6379

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    liquibase: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  backend:
    url: https://managerrent.com
  frontend:
    url: https://managerrent.com

geocoding:
  nominatim:
    url: https://nominatim.openstreetmap.org
    user-agent: RentalManagerApp/1.0
