spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres-db:5432/rental_manager}
    username: ${SPRING_DATASOURCE_USERNAME:${DB_USERNAME}}
    password: ${SPRING_DATASOURCE_PASSWORD:${DB_PASSWORD}}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml
  mail:
    host: ${SPRING_MAIL_HOST:smtp.gmail.com}
    port: ${SPRING_MAIL_PORT:587}
    username: ${EMAIL_ADDRESS}
    password: ${EMAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: ${MAIL_SMTP_AUTH:true}
          starttls:
            enable: ${MAIL_SMTP_STARTTLS:true}
  redis:
    host: ${SPRING_REDIS_HOST:redis}
    port: ${SPRING_REDIS_PORT:6379}

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    liquibase: INFO

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

app:
  backend:
    url: ${APP_BACKEND_URL:https://managerrent.com}
  frontend:
    url: ${APP_FRONTEND_URL:https://managerrent.com}

geocoding:
  nominatim:
    url: https://nominatim.openstreetmap.org
    user-agent: RentalManagerApp/1.0
