spring:
  datasource:
    url: jdbc:postgresql://postgres-db:5432/rental_manager
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master.xml

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    liquibase: INFO
    
